version: "3"
services:
  web:
    image: nginx
    ports:
    - "8000:80"
    - "4433:443"
    depends_on:
    - php
    volumes:
    - ../projects:/var/www # project dir
    - ../tmp/nginx/access.log:/var/log/nginx/access.log
    - ../tmp/nginx/error.log:/var/log/nginx/error.log

    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/conf.d:/etc/nginx/conf.d
    networks:
    - mynet

  php:
    build:
      context: ./
      dockerfile: Dockerfile_php
    volumes:
    - ../projects:/var/www # project dir
    networks:
    - mynet

  redis:
    image: circleci/redis
    ports:
    - "6379:6379"
    networks:
    - mynet
    
  mongo:
    image: circleci/mongo
    ports:
    - "27017:27017"
    networks:
    - mynet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
    - "3310:3306"
    volumes:
    - ../tmp/mysql/data:/var/lib/mysql
    networks:
    - mynet

networks:
  mynet:

