version: "3"
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    - "4433:443"
    depends_on:
    - php
    volumes:
    - /mnt/hgfs/project/php:/var/www # project dir
    - /srv/logs/access.log:/var/log/nginx/access.log
    - /srv/logs/error.log:/var/log/nginx/error.log

    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/conf.d:/etc/nginx/conf.d
    networks:
    - mynet

  php:
    build:
      context: ./
      dockerfile: Dockerfile_php
    volumes:
    - /mnt/hgfs/project/php:/var/www # project dir
    networks:
    - mynet

networks:
  mynet:

