version: "3"
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    - "4433:443"
    depends_on:
    - php
    volumes:
    - /srv/www:/var/www
    - /srv/logs/access.log:/var/log/nginx/access.log
    - /srv/logs/error.log:/var/log/nginx/error.log

    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/conf.d:/etc/nginx/conf.d
    networks:
    - mynet

  php:
    build:
      context: ./
      dockerfile: Dockerfile_php
    volumes:
    - /srv/www:/var/www
    networks:
    - mynet

  mysql:
    image: fukuyama012/mysql5.7
    ports:
    - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
    - mynet

networks:
  mynet:

